# basic flow to build docker image
name: CI docker build

# Controls when the action will run. 
on:
  push:
    tags:
      - '*'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}   
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          
      - name: docker build 
        run: |
          docker build -t ilyde/mlflow:${{ steps.get_version.outputs.VERSION }}
          
      - name: docker push
        run: |
          docker push ilyde/mlflow:${{ steps.get_version.outputs.VERSION }}
     
          echo test, and deploy your project.
